### ISSUE TITLE
Wrong year in repository description

### ISSUE THREAD

**Issue by cszach** [buildo/eslint-plugin-no-loops#13]
It's 2020.

![Screenshot from 2020-01-23 21-53-14](https://user-images.githubusercontent.com/24489228/72995073-32af0e00-3df0-11ea-9ae7-d41d4e845e36.png)

**Comment by gabro** [comment]
Indeed. Fixed, thanks!

**Comment by tjjfvi** [comment]
It's 2021 now ;)
