### ISSUE TITLE
Wrong year in repository description (2021 Update)

### ISSUE THREAD

**Issue by cszach** [buildo/eslint-plugin-no-loops#15]
It's 2021.
![Screenshot from 2021-01-30 20-27-22](https://user-images.githubusercontent.com/24489228/106357608-a9eb7c00-6339-11eb-9c26-71a829ccbb9d.png)

**Comment by gabro** [comment]
Fixed, thanks :)

**Comment by cszach** [comment]
@gabro No problem, see you in 2022.
